// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	posts "cms/internal/handler/posts"
	"cms/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/posts",
				Handler: posts.GetPostsHandler(serverCtx),
			},
		},
	)
}
