// Code generated by goctl. DO NOT EDIT.
package types

type Post struct {
	Id        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type GetPostsReq struct {
}

type GetPostsResp struct {
	List  []Post `json:"list"`
	Total int    `json:"total"`
}
